project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "!ignored"
  preview:
    port: 3998

website:
  title: "Beehive Beach Notes"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      - cosmo
      - styles.scss

execute:
  freeze: auto
bibliography: datadavev.bib
csl: chicago-author-date.csl
